<a href="https://colab.research.google.com/github/ImAli0/ML_and_DataScience/blob/main/18-Naive-Bayes-and-NLP/Feature_Extraction_from_Text.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Feature Extraction with Scikit-Learn

In [12]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfTransformer, TfidfVectorizer
from sklearn.pipeline import make_pipeline

## CountVectorizer

In [2]:
text = ['This is me', 'This is again me', 'Completely different me']
cv = CountVectorizer()
cv.fit_transform(text)

<3x6 sparse matrix of type '<class 'numpy.int64'>'
	with 10 stored elements in Compressed Sparse Row format>

In [4]:
sparse_mat = cv.fit_transform(text)
sparse_mat.todense()

matrix([[0, 0, 0, 1, 1, 1],
        [1, 0, 0, 1, 1, 1],
        [0, 1, 1, 0, 1, 0]])

In [5]:
cv.vocabulary_

{'this': 5, 'is': 3, 'me': 4, 'again': 0, 'completely': 1, 'different': 2}

In [6]:
cv = CountVectorizer(stop_words='english')
cv.fit_transform(text).todense()

matrix([[0, 0],
        [0, 0],
        [1, 1]])

In [7]:
cv.vocabulary_

{'completely': 0, 'different': 1}

## TfidfTransformer

In [8]:
tfidf_transformer = TfidfTransformer()
cv = CountVectorizer()
counts = cv.fit_transform(text)
counts

<3x6 sparse matrix of type '<class 'numpy.int64'>'
	with 10 stored elements in Compressed Sparse Row format>

In [9]:
tfidf = tfidf_transformer.fit_transform(counts)
tfidf

<3x6 sparse matrix of type '<class 'numpy.float64'>'
	with 10 stored elements in Compressed Sparse Row format>

In [10]:
tfidf.todense()

matrix([[0.        , 0.        , 0.        , 0.61980538, 0.48133417,
         0.61980538],
        [0.63174505, 0.        , 0.        , 0.4804584 , 0.37311881,
         0.4804584 ],
        [0.        , 0.65249088, 0.65249088, 0.        , 0.38537163,
         0.        ]])

In [13]:
pipe = make_pipeline(CountVectorizer(), TfidfTransformer())
results = pipe.fit_transform(text)
results

<3x6 sparse matrix of type '<class 'numpy.float64'>'
	with 10 stored elements in Compressed Sparse Row format>

In [15]:
results.todense()

matrix([[0.        , 0.        , 0.        , 0.61980538, 0.48133417,
         0.61980538],
        [0.63174505, 0.        , 0.        , 0.4804584 , 0.37311881,
         0.4804584 ],
        [0.        , 0.65249088, 0.65249088, 0.        , 0.38537163,
         0.        ]])

## TfidfVectorizer

In [16]:
tfidf = TfidfVectorizer()
new = tfidf.fit_transform(text)
new.todense()

matrix([[0.        , 0.        , 0.        , 0.61980538, 0.48133417,
         0.61980538],
        [0.63174505, 0.        , 0.        , 0.4804584 , 0.37311881,
         0.4804584 ],
        [0.        , 0.65249088, 0.65249088, 0.        , 0.38537163,
         0.        ]])