<a href="https://colab.research.google.com/github/ImAli0/ML_and_DataScience/blob/main/08-Linear-Regression-Models/03_My%20Regularization-Ridge-Lasso-ElasticNet.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df=pd.read_csv('Advertising.csv')
X=df.drop('sales',axis=1)
y=df['sales']

In [3]:
from sklearn.preprocessing import PolynomialFeatures

In [4]:
polynomial_converter=PolynomialFeatures(degree=3,include_bias=False)
poly_features=polynomial_converter.fit_transform(X)

In [5]:
poly_features

array([[2.30100000e+02, 3.78000000e+01, 6.92000000e+01, ...,
        9.88757280e+04, 1.81010592e+05, 3.31373888e+05],
       [4.45000000e+01, 3.93000000e+01, 4.51000000e+01, ...,
        6.96564990e+04, 7.99365930e+04, 9.17338510e+04],
       [1.72000000e+01, 4.59000000e+01, 6.93000000e+01, ...,
        1.46001933e+05, 2.20434291e+05, 3.32812557e+05],
       ...,
       [1.77000000e+02, 9.30000000e+00, 6.40000000e+00, ...,
        5.53536000e+02, 3.80928000e+02, 2.62144000e+02],
       [2.83600000e+02, 4.20000000e+01, 6.62000000e+01, ...,
        1.16776800e+05, 1.84062480e+05, 2.90117528e+05],
       [2.32100000e+02, 8.60000000e+00, 8.70000000e+00, ...,
        6.43452000e+02, 6.50934000e+02, 6.58503000e+02]])

In [6]:
from sklearn.model_selection import train_test_split

In [28]:
X_train, X_test, y_train, y_test = train_test_split( poly_features, y, test_size=0.3, random_state=101)

In [8]:
from sklearn.preprocessing import StandardScaler

In [9]:
# help(StandardScaler)

In [29]:
scaler=StandardScaler()

In [11]:
scaler

StandardScaler()

In [30]:
scaler.fit(X_train)

StandardScaler()

In [31]:
X_train=scaler.transform(X_train)

In [32]:
X_test=scaler.transform(X_test)

In [33]:
X_test

array([[-0.91339472,  1.76259419,  0.68168558, ...,  2.09516506,
         0.89465642,  0.09868885],
       [ 1.23121149,  0.23655959, -1.19601922, ..., -0.62566104,
        -0.60402516, -0.54547726],
       [-0.46002473, -0.40776614,  0.35005115, ..., -0.43068575,
        -0.23635113, -0.15776394],
       ...,
       [-1.33115973,  1.19965698, -1.18200649, ..., -0.47847952,
        -0.59569585, -0.54528297],
       [ 1.3522684 , -0.23142436, -1.4389064 , ..., -0.7233135 ,
        -0.61591305, -0.54660193],
       [ 0.27818504, -0.06186496,  0.01841672, ..., -0.32290124,
        -0.28905624, -0.33528306]])

In [34]:
X_train

array([[ 0.49300171, -0.33994238,  1.61586707, ..., -0.16360242,
         0.54694754,  1.37075536],
       [ 1.61337153,  1.32852213,  1.90079242, ...,  2.63236858,
         2.6297449 ,  1.95593378],
       [-0.84811893, -1.58789957, -1.02319564, ..., -0.72634944,
        -0.61593941, -0.54133745],
       ...,
       [ 1.04606563, -1.30982215,  0.27064572, ..., -0.71065643,
        -0.53420112, -0.20690952],
       [ 0.74817069,  0.03987068, -1.26608283, ..., -0.66805936,
        -0.61031703, -0.54616941],
       [ 0.13813882,  0.55533126,  1.01799092, ...,  0.61006767,
         0.67881488,  0.45425942]])

In [35]:
poly_features

array([[2.30100000e+02, 3.78000000e+01, 6.92000000e+01, ...,
        9.88757280e+04, 1.81010592e+05, 3.31373888e+05],
       [4.45000000e+01, 3.93000000e+01, 4.51000000e+01, ...,
        6.96564990e+04, 7.99365930e+04, 9.17338510e+04],
       [1.72000000e+01, 4.59000000e+01, 6.93000000e+01, ...,
        1.46001933e+05, 2.20434291e+05, 3.32812557e+05],
       ...,
       [1.77000000e+02, 9.30000000e+00, 6.40000000e+00, ...,
        5.53536000e+02, 3.80928000e+02, 2.62144000e+02],
       [2.83600000e+02, 4.20000000e+01, 6.62000000e+01, ...,
        1.16776800e+05, 1.84062480e+05, 2.90117528e+05],
       [2.32100000e+02, 8.60000000e+00, 8.70000000e+00, ...,
        6.43452000e+02, 6.50934000e+02, 6.58503000e+02]])

In [18]:
from sklearn.linear_model import Ridge

In [19]:
ridge_model = Ridge(alpha=10)

In [36]:
ridge_model.fit(X_train, y_train)

Ridge(alpha=10)

In [37]:
test_predictions = ridge_model.predict(X_test)

In [24]:
from sklearn.metrics import mean_absolute_error, mean_squared_error

In [49]:
MAE = mean_absolute_error(y_test, test_predictions)
MSE = mean_squared_error(y_test, test_predictions)
RMSE = np.sqrt(MSE)

In [39]:
MAE

0.5774404204714163

In [40]:
RMSE

0.894638646131965

In [41]:
# Training Set Performance
train_predictions = ridge_model.predict(X_train)
MAE = mean_absolute_error(y_train,train_predictions)
MAE

0.5288348183025309

In [42]:
from sklearn.linear_model import RidgeCV

In [44]:
# help(RidgeCV)

In [45]:
ridge_cv_model = RidgeCV(alphas=(0.2,2,11), scoring= 'neg_mean_absolute_error')

In [46]:
ridge_cv_model.fit(X_train, y_train)

RidgeCV(alphas=(0.2, 2, 11), scoring='neg_mean_absolute_error')

In [47]:
ridge_cv_model.alpha_

0.2

In [48]:
test_predictions = ridge_cv_model.predict(X_test)

In [51]:
MAE = mean_absolute_error(y_test, test_predictions)
MSE = mean_squared_error(y_test, test_predictions)
RMSE = np.sqrt(MSE)

In [52]:
MAE

0.4581942746861562

In [53]:
RMSE

0.6491167845145928

In [54]:
train_predictions = ridge_cv_model.predict(X_train)
MAE = mean_absolute_error(y_train,train_predictions)
MAE

0.33737203848923186

In [55]:
ridge_cv_model.coef_

array([ 4.66885180e+00,  6.23083991e-01,  4.03192053e-01, -4.38998430e+00,
        4.19068676e+00, -8.56154772e-01, -9.53841816e-01,  4.83162340e-01,
       -2.90403860e-01,  1.50659425e+00, -1.19643985e+00,  4.94170275e-01,
        8.93663357e-01, -2.16952766e-01,  2.29996891e-01,  2.26723786e-01,
       -1.67786393e-01,  2.55025601e-02,  9.57626894e-04])